"""Every Suppuo feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 70 feature routes of the Suppuo API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    def api_keys_create(self, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an api key (POST /api/v1/api-keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("api_keys_create needs name")
        return self._call("POST", f"/api/v1/api-keys", {}, payload)

    def api_keys_delete(self, id_: str) -> Any:
        """Delete an api key (DELETE /api/v1/api-keys/{id})."""
        return self._call("DELETE", f"/api/v1/api-keys/{_q(id_)}", {}, None)

    def api_keys_list(self) -> Any:
        """List api keys (GET /api/v1/api-keys)."""
        return self._call("GET", f"/api/v1/api-keys", {}, None)

    def attachments_create(self, *, length: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an attachment (POST /api/v1/attachments).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if length is not None:
            payload["length"] = length
        return self._call("POST", f"/api/v1/attachments", {}, payload)

    def attachments_get(self, id_: str) -> Any:
        """Get an attachment (GET /api/v1/attachments/{id})."""
        return self._call("GET", f"/api/v1/attachments/{_q(id_)}", {}, None)

    def billing_checkout(self, *, tier: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl. (POST /api/v1/billing/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        tier: one of free, starter, growth, business"""
        payload: Dict[str, Any] = dict(json_body or {})
        if tier is not None:
            payload["tier"] = tier
        if "tier" not in payload:
            raise ValueError("billing_checkout needs tier")
        return self._call("POST", f"/api/v1/billing/checkout", {}, payload)

    def billing_list(self) -> Any:
        """Current subscription (free default when no row) + the tier table the portal renders. (GET /api/v1/billing)."""
        return self._call("GET", f"/api/v1/billing", {}, None)

    def canned_replies_create(self, *, title: Optional[str] = None, body: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a canned reply (POST /api/v1/canned-replies).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        if "title" not in payload:
            raise ValueError("canned_replies_create needs title")
        if "body" not in payload:
            raise ValueError("canned_replies_create needs body")
        return self._call("POST", f"/api/v1/canned-replies", {}, payload)

    def canned_replies_delete(self, id_: str) -> Any:
        """Delete a canned reply (DELETE /api/v1/canned-replies/{id})."""
        return self._call("DELETE", f"/api/v1/canned-replies/{_q(id_)}", {}, None)

    def canned_replies_list(self) -> Any:
        """List canned replies (GET /api/v1/canned-replies)."""
        return self._call("GET", f"/api/v1/canned-replies", {}, None)

    def canned_replies_update(self, id_: str, *, title: Optional[str] = None, body: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a canned reply (PATCH /api/v1/canned-replies/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        return self._call("PATCH", f"/api/v1/canned-replies/{_q(id_)}", {}, payload)

    def channels_create(self) -> Any:
        """Create a channel (POST /api/v1/channels)."""
        return self._call("POST", f"/api/v1/channels", {}, None)

    def channels_delete(self, id_: str) -> Any:
        """Delete a channel (DELETE /api/v1/channels/{id})."""
        return self._call("DELETE", f"/api/v1/channels/{_q(id_)}", {}, None)

    def channels_list(self) -> Any:
        """List channels (GET /api/v1/channels)."""
        return self._call("GET", f"/api/v1/channels", {}, None)

    def csat_stats(self) -> Any:
        """List stats (GET /api/v1/csat/stats)."""
        return self._call("GET", f"/api/v1/csat/stats", {}, None)

    def domains_create(self, *, domain: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a domain (POST /api/v1/domains).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if domain is not None:
            payload["domain"] = domain
        if "domain" not in payload:
            raise ValueError("domains_create needs domain")
        return self._call("POST", f"/api/v1/domains", {}, payload)

    def domains_delete(self, id_: str) -> Any:
        """Delete a domain (DELETE /api/v1/domains/{id})."""
        return self._call("DELETE", f"/api/v1/domains/{_q(id_)}", {}, None)

    def domains_list(self) -> Any:
        """List domains (GET /api/v1/domains)."""
        return self._call("GET", f"/api/v1/domains", {}, None)

    def domains_verify(self, id_: str) -> Any:
        """Verify a domain (POST /api/v1/domains/{id}/verify)."""
        return self._call("POST", f"/api/v1/domains/{_q(id_)}/verify", {}, None)

    def help_articles(self) -> Any:
        """List articles (GET /api/v1/help/articles)."""
        return self._call("GET", f"/api/v1/help/articles", {}, None)

    def help_articles_2(self, id_: str) -> Any:
        """Get an article (GET /api/v1/help/articles/{id})."""
        return self._call("GET", f"/api/v1/help/articles/{_q(id_)}", {}, None)

    def help_create_articles(self, *, kind: Optional[str] = None, slug: Optional[str] = None, category: Optional[str] = None, title: Optional[str] = None, body: Optional[str] = None, status: Optional[str] = None, position: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an article (POST /api/v1/help/articles).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        kind: one of faq, article
        status: one of draft, published"""
        payload: Dict[str, Any] = dict(json_body or {})
        if kind is not None:
            payload["kind"] = kind
        if slug is not None:
            payload["slug"] = slug
        if category is not None:
            payload["category"] = category
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        if status is not None:
            payload["status"] = status
        if position is not None:
            payload["position"] = position
        if "title" not in payload:
            raise ValueError("help_create_articles needs title")
        if "body" not in payload:
            raise ValueError("help_create_articles needs body")
        return self._call("POST", f"/api/v1/help/articles", {}, payload)

    def help_delete_articles(self, id_: str) -> Any:
        """Delete an article (DELETE /api/v1/help/articles/{id})."""
        return self._call("DELETE", f"/api/v1/help/articles/{_q(id_)}", {}, None)

    def help_update_articles(self, id_: str, *, kind: Optional[str] = None, slug: Optional[str] = None, category: Optional[str] = None, title: Optional[str] = None, body: Optional[str] = None, status: Optional[str] = None, position: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update an article (PATCH /api/v1/help/articles/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        kind: one of faq, article
        status: one of draft, published"""
        payload: Dict[str, Any] = dict(json_body or {})
        if kind is not None:
            payload["kind"] = kind
        if slug is not None:
            payload["slug"] = slug
        if category is not None:
            payload["category"] = category
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        if status is not None:
            payload["status"] = status
        if position is not None:
            payload["position"] = position
        return self._call("PATCH", f"/api/v1/help/articles/{_q(id_)}", {}, payload)

    def me_list(self) -> Any:
        """List me (GET /api/v1/me)."""
        return self._call("GET", f"/api/v1/me", {}, None)

    def profile_avatar(self, sub: str) -> Any:
        """Get an avatar (GET /api/v1/profile/avatar/{sub})."""
        return self._call("GET", f"/api/v1/profile/avatar/{_q(sub)}", {}, None)

    def profile_delete_avatar(self) -> Any:
        """Delete avatar (DELETE /api/v1/profile/avatar)."""
        return self._call("DELETE", f"/api/v1/profile/avatar", {}, None)

    def profile_set_avatar(self, *, length: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Set avatar (PUT /api/v1/profile/avatar).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if length is not None:
            payload["length"] = length
        return self._call("PUT", f"/api/v1/profile/avatar", {}, payload)

    def public_create_tickets(self, *, account_id: Optional[str] = None, subject: Optional[str] = None, body: Optional[str] = None, email: Optional[str] = None, name: Optional[str] = None, company: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a ticket (POST /api/v1/public/tickets).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if account_id is not None:
            payload["accountId"] = account_id
        if subject is not None:
            payload["subject"] = subject
        if body is not None:
            payload["body"] = body
        if email is not None:
            payload["email"] = email
        if name is not None:
            payload["name"] = name
        if company is not None:
            payload["company"] = company
        if "accountId" not in payload:
            raise ValueError("public_create_tickets needs account_id")
        if "subject" not in payload:
            raise ValueError("public_create_tickets needs subject")
        if "body" not in payload:
            raise ValueError("public_create_tickets needs body")
        if "email" not in payload:
            raise ValueError("public_create_tickets needs email")
        return self._call("POST", f"/api/v1/public/tickets", {}, payload)

    def public_create_tickets_attachments(self, access_token: str, *, length: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Attachments a ticket (POST /api/v1/public/tickets/{accessToken}/attachments).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if length is not None:
            payload["length"] = length
        return self._call("POST", f"/api/v1/public/tickets/{_q(access_token)}/attachments", {}, payload)

    def public_domains_provision_callback(self, *, domain: Optional[str] = None, status: Optional[str] = None, error: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a provision callback (POST /api/v1/public/domains/provision-callback).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        status: one of success, failed"""
        payload: Dict[str, Any] = dict(json_body or {})
        if domain is not None:
            payload["domain"] = domain
        if status is not None:
            payload["status"] = status
        if error is not None:
            payload["error"] = error
        if "domain" not in payload:
            raise ValueError("public_domains_provision_callback needs domain")
        if "status" not in payload:
            raise ValueError("public_domains_provision_callback needs status")
        return self._call("POST", f"/api/v1/public/domains/provision-callback", {}, payload)

    def public_domains_resolve(self, *, host: Optional[Any] = None) -> Any:
        """Host → accountId — used by the frontend middleware to route a custom domain's request to the right workspace. (GET /api/v1/public/domains/resolve)."""
        return self._call("GET", f"/api/v1/public/domains/resolve", {"host": host}, None)

    def public_help(self, account_id: str) -> Any:
        """The help-center bundle. (GET /api/v1/public/help/{accountId})."""
        return self._call("GET", f"/api/v1/public/help/{_q(account_id)}", {}, None)

    def public_help_a(self, account_id: str, slug: str) -> Any:
        """A single published article. (GET /api/v1/public/help/{accountId}/a/{slug})."""
        return self._call("GET", f"/api/v1/public/help/{_q(account_id)}/a/{_q(slug)}", {}, None)

    def public_help_branding(self, account_id: str) -> Any:
        """Public branding (logo + colors + name) for the help center AND the hosted portal's pre-auth screen. (GET /api/v1/public/help/{accountId}/branding)."""
        return self._call("GET", f"/api/v1/public/help/{_q(account_id)}/branding", {}, None)

    def public_help_logo(self, account_id: str) -> Any:
        """Serve the uploaded brand logo bytes. (GET /api/v1/public/help/{accountId}/logo)."""
        return self._call("GET", f"/api/v1/public/help/{_q(account_id)}/logo", {}, None)

    def public_help_search(self, account_id: str, *, q: Optional[str] = None) -> Any:
        """List search (GET /api/v1/public/help/{accountId}/search)."""
        return self._call("GET", f"/api/v1/public/help/{_q(account_id)}/search", {"q": q}, None)

    def public_requester_verify(self, *, token: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a verify (POST /api/v1/public/requester/verify).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if token is not None:
            payload["token"] = token
        if "token" not in payload:
            raise ValueError("public_requester_verify needs token")
        return self._call("POST", f"/api/v1/public/requester/verify", {}, payload)

    def public_tickets(self, access_token: str) -> Any:
        """Tokenized status view — public messages only, no internal notes. (GET /api/v1/public/tickets/{accessToken})."""
        return self._call("GET", f"/api/v1/public/tickets/{_q(access_token)}", {}, None)

    def public_tickets_attachments(self, access_token: str, id_: str) -> Any:
        """Get an attachment (GET /api/v1/public/tickets/{accessToken}/attachments/{id})."""
        return self._call("GET", f"/api/v1/public/tickets/{_q(access_token)}/attachments/{_q(id_)}", {}, None)

    def public_tickets_csat(self, access_token: str, *, score: Optional[int] = None, comment: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Csat a ticket (POST /api/v1/public/tickets/{accessToken}/csat).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if score is not None:
            payload["score"] = score
        if comment is not None:
            payload["comment"] = comment
        if "score" not in payload:
            raise ValueError("public_tickets_csat needs score")
        return self._call("POST", f"/api/v1/public/tickets/{_q(access_token)}/csat", {}, payload)

    def public_tickets_messages(self, access_token: str, *, body: Optional[str] = None, attachment_ids: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Messages a ticket (POST /api/v1/public/tickets/{accessToken}/messages).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if body is not None:
            payload["body"] = body
        if attachment_ids is not None:
            payload["attachmentIds"] = attachment_ids
        if "body" not in payload:
            raise ValueError("public_tickets_messages needs body")
        return self._call("POST", f"/api/v1/public/tickets/{_q(access_token)}/messages", {}, payload)

    def public_widget_config(self, *, account: Optional[Any] = None) -> Any:
        """Pre-ticket config for the embeddable widget + hosted form (the branding footer renders before any ticket exists). (GET /api/v1/public/widget-config)."""
        return self._call("GET", f"/api/v1/public/widget-config", {"account": account}, None)

    def reports_summary(self, *, days: Optional[Any] = None) -> Any:
        """List summary (GET /api/v1/reports/summary)."""
        return self._call("GET", f"/api/v1/reports/summary", {"days": days}, None)

    def requester_create_tickets(self, *, subject: Optional[str] = None, body: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a ticket (POST /api/v1/requester/tickets).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if subject is not None:
            payload["subject"] = subject
        if body is not None:
            payload["body"] = body
        if "subject" not in payload:
            raise ValueError("requester_create_tickets needs subject")
        if "body" not in payload:
            raise ValueError("requester_create_tickets needs body")
        return self._call("POST", f"/api/v1/requester/tickets", {}, payload)

    def requester_me(self) -> Any:
        """List me (GET /api/v1/requester/me)."""
        return self._call("GET", f"/api/v1/requester/me", {}, None)

    def requester_tickets(self, *, status: Optional[str] = None) -> Any:
        """List tickets (GET /api/v1/requester/tickets)."""
        return self._call("GET", f"/api/v1/requester/tickets", {"status": status}, None)

    def requester_tickets_2(self, number: str) -> Any:
        """Get a ticket (GET /api/v1/requester/tickets/{number})."""
        return self._call("GET", f"/api/v1/requester/tickets/{_q(number)}", {}, None)

    def requester_tickets_messages(self, number: str, *, body: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Messages a ticket (POST /api/v1/requester/tickets/{number}/messages).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if body is not None:
            payload["body"] = body
        if "body" not in payload:
            raise ValueError("requester_tickets_messages needs body")
        return self._call("POST", f"/api/v1/requester/tickets/{_q(number)}/messages", {}, payload)

    def settings_automation(self) -> Any:
        """List automation (GET /api/v1/settings/automation)."""
        return self._call("GET", f"/api/v1/settings/automation", {}, None)

    def settings_branding(self) -> Any:
        """List branding (GET /api/v1/settings/branding)."""
        return self._call("GET", f"/api/v1/settings/branding", {}, None)

    def settings_create_branding_logo(self, *, length: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a logo (POST /api/v1/settings/branding/logo).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if length is not None:
            payload["length"] = length
        return self._call("POST", f"/api/v1/settings/branding/logo", {}, payload)

    def settings_delete_branding_logo(self) -> Any:
        """Delete logo (DELETE /api/v1/settings/branding/logo)."""
        return self._call("DELETE", f"/api/v1/settings/branding/logo", {}, None)

    def settings_help(self) -> Any:
        """List help (GET /api/v1/settings/help)."""
        return self._call("GET", f"/api/v1/settings/help", {}, None)

    def settings_set_automation(self, *, business_hours: Optional[Dict[str, Any]] = None, auto_response_enabled: Optional[bool] = None, auto_response_inside: Optional[str] = None, auto_response_outside: Optional[str] = None, hide_branding: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Set automation (PUT /api/v1/settings/automation).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if business_hours is not None:
            payload["businessHours"] = business_hours
        if auto_response_enabled is not None:
            payload["autoResponseEnabled"] = auto_response_enabled
        if auto_response_inside is not None:
            payload["autoResponseInside"] = auto_response_inside
        if auto_response_outside is not None:
            payload["autoResponseOutside"] = auto_response_outside
        if hide_branding is not None:
            payload["hideBranding"] = hide_branding
        return self._call("PUT", f"/api/v1/settings/automation", {}, payload)

    def settings_set_branding(self, *, slug: Optional[str] = None, brand_name: Optional[str] = None, brand_logo_url: Optional[str] = None, accent_color: Optional[Any] = None, brand_color: Optional[Any] = None, widget_text_color: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Set branding (PUT /api/v1/settings/branding).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if slug is not None:
            payload["slug"] = slug
        if brand_name is not None:
            payload["brandName"] = brand_name
        if brand_logo_url is not None:
            payload["brandLogoUrl"] = brand_logo_url
        if accent_color is not None:
            payload["accentColor"] = accent_color
        if brand_color is not None:
            payload["brandColor"] = brand_color
        if widget_text_color is not None:
            payload["widgetTextColor"] = widget_text_color
        return self._call("PUT", f"/api/v1/settings/branding", {}, payload)

    def settings_set_help(self, *, contact_email: Optional[Any] = None, contact_phone: Optional[str] = None, contact_address: Optional[str] = None, docs_url: Optional[str] = None, contact_url: Optional[str] = None, help_intro: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Set help (PUT /api/v1/settings/help).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if contact_email is not None:
            payload["contactEmail"] = contact_email
        if contact_phone is not None:
            payload["contactPhone"] = contact_phone
        if contact_address is not None:
            payload["contactAddress"] = contact_address
        if docs_url is not None:
            payload["docsUrl"] = docs_url
        if contact_url is not None:
            payload["contactUrl"] = contact_url
        if help_intro is not None:
            payload["helpIntro"] = help_intro
        return self._call("PUT", f"/api/v1/settings/help", {}, payload)

    def tickets_create(self, *, subject: Optional[str] = None, body: Optional[str] = None, requester_email: Optional[str] = None, requester_name: Optional[str] = None, priority: Optional[str] = None, channel: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Agent-created ticket (logging an inquiry that arrived out-of-band, e.g. (POST /api/v1/tickets).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        channel: one of web, email, whatsapp"""
        payload: Dict[str, Any] = dict(json_body or {})
        if subject is not None:
            payload["subject"] = subject
        if body is not None:
            payload["body"] = body
        if requester_email is not None:
            payload["requesterEmail"] = requester_email
        if requester_name is not None:
            payload["requesterName"] = requester_name
        if priority is not None:
            payload["priority"] = priority
        if channel is not None:
            payload["channel"] = channel
        if "subject" not in payload:
            raise ValueError("tickets_create needs subject")
        if "body" not in payload:
            raise ValueError("tickets_create needs body")
        if "requesterEmail" not in payload:
            raise ValueError("tickets_create needs requester_email")
        return self._call("POST", f"/api/v1/tickets", {}, payload)

    def tickets_get(self, id_: str) -> Any:
        """Get a ticket (GET /api/v1/tickets/{id})."""
        return self._call("GET", f"/api/v1/tickets/{_q(id_)}", {}, None)

    def tickets_list(self, *, status: Optional[str] = None, assignee: Optional[str] = None, tag: Optional[str] = None, channel: Optional[str] = None, priority: Optional[str] = None, q: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> Any:
        """List tickets (GET /api/v1/tickets)."""
        return self._call("GET", f"/api/v1/tickets", {"status": status, "assignee": assignee, "tag": tag, "channel": channel, "priority": priority, "q": q, "limit": limit, "cursor": cursor}, None)

    def tickets_messages(self, id_: str, *, body: Optional[str] = None, is_internal: Optional[bool] = None, author_name: Optional[str] = None, attachment_ids: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Messages a ticket (POST /api/v1/tickets/{id}/messages).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if body is not None:
            payload["body"] = body
        if is_internal is not None:
            payload["isInternal"] = is_internal
        if author_name is not None:
            payload["authorName"] = author_name
        if attachment_ids is not None:
            payload["attachmentIds"] = attachment_ids
        if "body" not in payload:
            raise ValueError("tickets_messages needs body")
        return self._call("POST", f"/api/v1/tickets/{_q(id_)}/messages", {}, payload)

    def tickets_tags(self) -> Any:
        """Distinct tags across the workspace's tickets — autocomplete feed. (GET /api/v1/tickets/tags)."""
        return self._call("GET", f"/api/v1/tickets/tags", {}, None)

    def tickets_update(self, id_: str, *, status: Optional[str] = None, priority: Optional[str] = None, assignee_sub: Optional[str] = None, tags: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a ticket (PATCH /api/v1/tickets/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if status is not None:
            payload["status"] = status
        if priority is not None:
            payload["priority"] = priority
        if assignee_sub is not None:
            payload["assigneeSub"] = assignee_sub
        if tags is not None:
            payload["tags"] = tags
        return self._call("PATCH", f"/api/v1/tickets/{_q(id_)}", {}, payload)

    def webhook_subscriptions_create(self, *, url: Optional[str] = None, events: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a webhook subscription (POST /api/v1/webhook-subscriptions).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if "url" not in payload:
            raise ValueError("webhook_subscriptions_create needs url")
        return self._call("POST", f"/api/v1/webhook-subscriptions", {}, payload)

    def webhook_subscriptions_delete(self, id_: str) -> Any:
        """Delete a webhook subscription (DELETE /api/v1/webhook-subscriptions/{id})."""
        return self._call("DELETE", f"/api/v1/webhook-subscriptions/{_q(id_)}", {}, None)

    def webhook_subscriptions_list(self) -> Any:
        """List webhook subscriptions (GET /api/v1/webhook-subscriptions)."""
        return self._call("GET", f"/api/v1/webhook-subscriptions", {}, None)

    def webhook_subscriptions_update(self, id_: str, *, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a webhook subscription (PATCH /api/v1/webhook-subscriptions/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if active is not None:
            payload["active"] = active
        if "active" not in payload:
            raise ValueError("webhook_subscriptions_update needs active")
        return self._call("PATCH", f"/api/v1/webhook-subscriptions/{_q(id_)}", {}, payload)

    def webhooks_telegram(self, integration_id: str, *, secret: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Act on a telegram (POST /api/v1/webhooks/telegram/{integrationId})."""
        payload: Dict[str, Any] = dict(json_body or {})
        return self._call("POST", f"/api/v1/webhooks/telegram/{_q(integration_id)}", {"secret": secret}, payload)

    def webhooks_twilio_whatsapp(self, *, secret: Optional[Any] = None, body: Optional[Any] = None, from_: Optional[Any] = None, num_media: Optional[Any] = None, profile_name: Optional[Any] = None, to: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a whatsapp (POST /api/v1/webhooks/twilio/whatsapp).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if body is not None:
            payload["Body"] = body
        if from_ is not None:
            payload["From"] = from_
        if num_media is not None:
            payload["NumMedia"] = num_media
        if profile_name is not None:
            payload["ProfileName"] = profile_name
        if to is not None:
            payload["To"] = to
        return self._call("POST", f"/api/v1/webhooks/twilio/whatsapp", {"secret": secret}, payload)

    def webhooks_whatsapp_cloud(self, *, hub_challenge: Optional[Any] = None, hub_mode: Optional[Any] = None, hub_verify_token: Optional[Any] = None) -> Any:
        """GET — subscription verification handshake. (GET /api/v1/webhooks/whatsapp-cloud)."""
        return self._call("GET", f"/api/v1/webhooks/whatsapp-cloud", {"hub.challenge": hub_challenge, "hub.mode": hub_mode, "hub.verify_token": hub_verify_token}, None)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
