// Every Suppuo feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 67 feature routes of the Suppuo API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Delete an api key (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** Create an attachment (POST /api/v1/attachments) */
  attachmentsCreate(input?: { "length"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/attachments`, query, all);
  }

  /** Get an attachment (GET /api/v1/attachments/{id}) */
  attachmentsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/attachments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl. (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "tier": "free" | "starter" | "growth" | "business"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** Current subscription (free default when no row) + the tier table the portal renders. (GET /api/v1/billing) */
  billingList(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing`, {}, undefined);
  }

  /** Create a canned reply (POST /api/v1/canned-replies) */
  cannedRepliesCreate(input: { "title": string; "body": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/canned-replies`, query, all);
  }

  /** Delete a canned reply (DELETE /api/v1/canned-replies/{id}) */
  cannedRepliesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/canned-replies/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List canned replies (GET /api/v1/canned-replies) */
  cannedRepliesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/canned-replies`, {}, undefined);
  }

  /** Update a canned reply (PATCH /api/v1/canned-replies/{id}) */
  cannedRepliesUpdate(id: string, input?: { "title"?: string; "body"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/canned-replies/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a channel (POST /api/v1/channels) */
  channelsCreate(input?: { "provider"?: "whatsapp_twilio" | "whatsapp_cloud" | "email_resend" | "telegram_bot" | "slack_webhook" | "discord_webhook"; "accountSid"?: string; "authToken"?: string; "whatsappNumber"?: string; "displayName"?: string; "accessToken"?: string; "phoneNumberId"?: string; "wabaId"?: string; "displayNumber"?: string; "verifyToken"?: string; "appSecret"?: string; "apiKey"?: string; "fromEmail"?: string; "fromName"?: string; "botToken"?: string; "webhookUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/channels`, query, all);
  }

  /** Delete a channel (DELETE /api/v1/channels/{id}) */
  channelsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/channels/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List channels (GET /api/v1/channels) */
  channelsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/channels`, {}, undefined);
  }

  /** List stats (GET /api/v1/csat/stats) */
  csatStats(): Promise<unknown> {
    return this.call("GET", `/api/v1/csat/stats`, {}, undefined);
  }

  /** Create a domain (POST /api/v1/domains) */
  domainsCreate(input: { "domain": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/domains`, query, all);
  }

  /** Delete a domain (DELETE /api/v1/domains/{id}) */
  domainsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/domains/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List domains (GET /api/v1/domains) */
  domainsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/domains`, {}, undefined);
  }

  /** Verify a domain (POST /api/v1/domains/{id}/verify) */
  domainsVerify(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/domains/${encodeURIComponent(id)}/verify`, {}, undefined);
  }

  /** List articles (GET /api/v1/help/articles) */
  helpArticles(): Promise<unknown> {
    return this.call("GET", `/api/v1/help/articles`, {}, undefined);
  }

  /** Create an article (POST /api/v1/help/articles) */
  helpCreateArticles(input: { "kind"?: "faq" | "article"; "slug"?: string; "category"?: string; "title": string; "body": string; "status"?: "draft" | "published"; "position"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/help/articles`, query, all);
  }

  /** Delete an article (DELETE /api/v1/help/articles/{id}) */
  helpDeleteArticles(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/help/articles/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get an article (GET /api/v1/help/articles/{id}) */
  helpGetArticles(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/help/articles/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Update an article (PATCH /api/v1/help/articles/{id}) */
  helpUpdateArticles(id: string, input?: { "kind"?: "faq" | "article"; "slug"?: string; "category"?: string; "title"?: string; "body"?: string; "status"?: "draft" | "published"; "position"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/help/articles/${encodeURIComponent(id)}`, query, all);
  }

  /** List me (GET /api/v1/me) */
  meList(): Promise<unknown> {
    return this.call("GET", `/api/v1/me`, {}, undefined);
  }

  /** Get an avatar (GET /api/v1/profile/avatar/{sub}) */
  profileAvatar(sub: string): Promise<unknown> {
    return this.call("GET", `/api/v1/profile/avatar/${encodeURIComponent(sub)}`, {}, undefined);
  }

  /** Delete avatar (DELETE /api/v1/profile/avatar) */
  profileDeleteAvatar(): Promise<unknown> {
    return this.call("DELETE", `/api/v1/profile/avatar`, {}, undefined);
  }

  /** Set avatar (PUT /api/v1/profile/avatar) */
  profileSetAvatar(input?: { "length"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/profile/avatar`, query, all);
  }

  /** Create a ticket (POST /api/v1/public/tickets) */
  publicCreateTickets(input: { "accountId": string; "subject": string; "body": string; "email": string; "name"?: string; "company"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/tickets`, query, all);
  }

  /** Attachments a ticket (POST /api/v1/public/tickets/{accessToken}/attachments) */
  publicCreateTicketsAttachments(accessToken: string, input?: { "length"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/tickets/${encodeURIComponent(accessToken)}/attachments`, query, all);
  }

  /** Create a provision callback (POST /api/v1/public/domains/provision-callback) */
  publicDomainsProvisionCallback(input: { "domain": string; "status": "success" | "failed"; "error"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/domains/provision-callback`, query, all);
  }

  /** Host → accountId — used by the frontend middleware to route a custom domain's request to the right workspace. (GET /api/v1/public/domains/resolve) */
  publicDomainsResolve(input?: { "host"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["host"] = all["host"]; delete all["host"];
    return this.call("GET", `/api/v1/public/domains/resolve`, query, undefined);
  }

  /** The help-center bundle. (GET /api/v1/public/help/{accountId}) */
  publicHelp(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/help/${encodeURIComponent(accountId)}`, {}, undefined);
  }

  /** A single published article. (GET /api/v1/public/help/{accountId}/a/{slug}) */
  publicHelpA(accountId: string, slug: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/help/${encodeURIComponent(accountId)}/a/${encodeURIComponent(slug)}`, {}, undefined);
  }

  /** Public branding (logo + colors + name) for the help center AND the hosted portal's pre-auth screen. (GET /api/v1/public/help/{accountId}/branding) */
  publicHelpBranding(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/help/${encodeURIComponent(accountId)}/branding`, {}, undefined);
  }

  /** Serve the uploaded brand logo bytes. (GET /api/v1/public/help/{accountId}/logo) */
  publicHelpLogo(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/help/${encodeURIComponent(accountId)}/logo`, {}, undefined);
  }

  /** List search (GET /api/v1/public/help/{accountId}/search) */
  publicHelpSearch(accountId: string, input?: { "q"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/public/help/${encodeURIComponent(accountId)}/search`, query, undefined);
  }

  /** Create a verify (POST /api/v1/public/requester/verify) */
  publicRequesterVerify(input: { "token": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/requester/verify`, query, all);
  }

  /** Tokenized status view — public messages only, no internal notes. (GET /api/v1/public/tickets/{accessToken}) */
  publicTickets(accessToken: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/tickets/${encodeURIComponent(accessToken)}`, {}, undefined);
  }

  /** Get an attachment (GET /api/v1/public/tickets/{accessToken}/attachments/{id}) */
  publicTicketsAttachments(accessToken: string, id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/tickets/${encodeURIComponent(accessToken)}/attachments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Csat a ticket (POST /api/v1/public/tickets/{accessToken}/csat) */
  publicTicketsCsat(accessToken: string, input: { "score": number; "comment"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/tickets/${encodeURIComponent(accessToken)}/csat`, query, all);
  }

  /** Messages a ticket (POST /api/v1/public/tickets/{accessToken}/messages) */
  publicTicketsMessages(accessToken: string, input: { "body": string; "attachmentIds"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/tickets/${encodeURIComponent(accessToken)}/messages`, query, all);
  }

  /** Pre-ticket config for the embeddable widget + hosted form (the branding footer renders before any ticket exists). (GET /api/v1/public/widget-config) */
  publicWidgetConfig(input?: { "account"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["account"] = all["account"]; delete all["account"];
    return this.call("GET", `/api/v1/public/widget-config`, query, undefined);
  }

  /** List summary (GET /api/v1/reports/summary) */
  reportsSummary(input?: { "days"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["days"] = all["days"]; delete all["days"];
    return this.call("GET", `/api/v1/reports/summary`, query, undefined);
  }

  /** Create a ticket (POST /api/v1/requester/tickets) */
  requesterCreateTickets(input: { "subject": string; "body": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/requester/tickets`, query, all);
  }

  /** Get a ticket (GET /api/v1/requester/tickets/{number}) */
  requesterGetTickets(number: string): Promise<unknown> {
    return this.call("GET", `/api/v1/requester/tickets/${encodeURIComponent(number)}`, {}, undefined);
  }

  /** List me (GET /api/v1/requester/me) */
  requesterMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/requester/me`, {}, undefined);
  }

  /** List tickets (GET /api/v1/requester/tickets) */
  requesterTickets(input?: { "status"?: "open" | "resolved" | "all" }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/requester/tickets`, query, undefined);
  }

  /** Messages a ticket (POST /api/v1/requester/tickets/{number}/messages) */
  requesterTicketsMessages(number: string, input: { "body": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/requester/tickets/${encodeURIComponent(number)}/messages`, query, all);
  }

  /** List automation (GET /api/v1/settings/automation) */
  settingsAutomation(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings/automation`, {}, undefined);
  }

  /** List branding (GET /api/v1/settings/branding) */
  settingsBranding(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings/branding`, {}, undefined);
  }

  /** Create a logo (POST /api/v1/settings/branding/logo) */
  settingsCreateBrandingLogo(input?: { "length"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/settings/branding/logo`, query, all);
  }

  /** Delete logo (DELETE /api/v1/settings/branding/logo) */
  settingsDeleteBrandingLogo(): Promise<unknown> {
    return this.call("DELETE", `/api/v1/settings/branding/logo`, {}, undefined);
  }

  /** List help (GET /api/v1/settings/help) */
  settingsHelp(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings/help`, {}, undefined);
  }

  /** Set automation (PUT /api/v1/settings/automation) */
  settingsSetAutomation(input?: { "businessHours"?: Record<string, unknown>; "autoResponseEnabled"?: boolean; "autoResponseInside"?: string; "autoResponseOutside"?: string; "hideBranding"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/settings/automation`, query, all);
  }

  /** Set branding (PUT /api/v1/settings/branding) */
  settingsSetBranding(input?: { "slug"?: string; "brandName"?: string; "brandLogoUrl"?: string; "accentColor"?: unknown; "brandColor"?: unknown; "widgetTextColor"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/settings/branding`, query, all);
  }

  /** Set help (PUT /api/v1/settings/help) */
  settingsSetHelp(input?: { "contactEmail"?: unknown; "contactPhone"?: string; "contactAddress"?: string; "docsUrl"?: string; "contactUrl"?: string; "helpIntro"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/settings/help`, query, all);
  }

  /** Agent-created ticket (logging an inquiry that arrived out-of-band, e.g. (POST /api/v1/tickets) */
  ticketsCreate(input: { "subject": string; "body": string; "requesterEmail": string; "requesterName"?: string; "priority"?: string; "channel"?: "web" | "email" | "whatsapp"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/tickets`, query, all);
  }

  /** Get a ticket (GET /api/v1/tickets/{id}) */
  ticketsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/tickets/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List tickets (GET /api/v1/tickets) */
  ticketsList(input?: { "status"?: "open" | "pending" | "resolved" | "closed" | "all"; "assignee"?: string; "tag"?: string; "channel"?: "web" | "email" | "whatsapp" | "telegram"; "priority"?: "low" | "normal" | "high" | "urgent"; "q"?: string; "limit"?: number; "cursor"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    query["assignee"] = all["assignee"]; delete all["assignee"];
    query["tag"] = all["tag"]; delete all["tag"];
    query["channel"] = all["channel"]; delete all["channel"];
    query["priority"] = all["priority"]; delete all["priority"];
    query["q"] = all["q"]; delete all["q"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    return this.call("GET", `/api/v1/tickets`, query, undefined);
  }

  /** Messages a ticket (POST /api/v1/tickets/{id}/messages) */
  ticketsMessages(id: string, input: { "body": string; "isInternal"?: boolean; "authorName"?: string; "attachmentIds"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/tickets/${encodeURIComponent(id)}/messages`, query, all);
  }

  /** Distinct tags across the workspace's tickets — autocomplete feed. (Must be mounted before /:id so 'tags' isn't read as a ticket id.) (GET /api/v1/tickets/tags) */
  ticketsTags(): Promise<unknown> {
    return this.call("GET", `/api/v1/tickets/tags`, {}, undefined);
  }

  /** Update a ticket (PATCH /api/v1/tickets/{id}) */
  ticketsUpdate(id: string, input?: { "status"?: string; "priority"?: string; "assigneeSub"?: string; "tags"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/tickets/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a webhook subscription (POST /api/v1/webhook-subscriptions) */
  webhookSubscriptionsCreate(input: { "url": string; "events"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhook-subscriptions`, query, all);
  }

  /** Delete a webhook subscription (DELETE /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List webhook subscriptions (GET /api/v1/webhook-subscriptions) */
  webhookSubscriptionsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-subscriptions`, {}, undefined);
  }

  /** Update a webhook subscription (PATCH /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsUpdate(id: string, input: { "active": boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, query, all);
  }

  /** @deprecated The old name of `helpGetArticles` (GET /api/v1/help/articles/{id}). */
  helpArticles2(...args: Parameters<GeneratedApi["helpGetArticles"]>): Promise<unknown> {
    return this.helpGetArticles(...args);
  }

  /** @deprecated The old name of `requesterGetTickets` (GET /api/v1/requester/tickets/{number}). */
  requesterTickets2(...args: Parameters<GeneratedApi["requesterGetTickets"]>): Promise<unknown> {
    return this.requesterGetTickets(...args);
  }
}
