#!/usr/bin/env node
/**
 * Build-time version generator (Forjio family shared mechanism).
 *
 * Captures the current build's version metadata from git and writes it to
 * `src/lib/version.ts` as plain string constants. Designed to run in a
 * `prebuild` / `predev` hook so the value is ALWAYS current — never a stale
 * hand-bumped package.json field.
 *
 * Resolution order for each field (first that works wins):
 *   1. git (the source of truth at build time)
 *   2. env vars (NEXT_PUBLIC_APP_VERSION / SOURCE_COMMIT — set by CI/PaaS
 *      builders where the .git dir may be absent)
 *   3. a safe 'dev' / 'unknown' fallback
 *
 * Intentionally generic: no product-specific assumptions. Copy this file
 * verbatim into any Forjio Next.js product.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(__dirname, '..', 'src', 'lib', 'version.ts');

/** Run a git command, returning trimmed stdout or null if git/repo absent. */
function git(args) {
  try {
    return execSync(`git ${args}`, {
      cwd: join(__dirname, '..'),
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

// version: prefer `git describe` (tag-aware, marks dirty trees), fall back to
// short SHA, then env, then 'dev'.
const describe = git('describe --tags --always --dirty');
const shortSha = git('rev-parse --short HEAD');
const version =
  describe || shortSha || process.env.NEXT_PUBLIC_APP_VERSION || 'dev';

// sha: the short commit. CI builders may pass SOURCE_COMMIT instead.
const sha =
  shortSha ||
  (process.env.SOURCE_COMMIT ? process.env.SOURCE_COMMIT.slice(0, 7) : null) ||
  'unknown';

const builtAt = new Date().toISOString();

const banner = `// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
`;

const contents = `${banner}export const APP_VERSION = ${JSON.stringify(version)};
export const BUILD_SHA = ${JSON.stringify(sha)};
export const BUILD_DATE = ${JSON.stringify(builtAt)};
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, contents);

console.log(`[gen-version] ${version} (${sha}) @ ${builtAt}`);
