// apigen cli — every feature route of a product as a CLI command, from its openapi.json.
//
//   node <apigen>/cli.mjs --spec backend/openapi.json --out cli/src/commands/api.generated.ts
//
// Writes one TypeScript file: the route table plus a small builder that turns it into
//   <brand> api <area> <action> [path params…] [--field value …] [--body JSON]
// e.g. `ripllo api discount-codes create --code SPRING10 --type percent --value 10 --currency IDR`.
// The call itself goes through the product's own client via `callRoute` in
// `cli/src/lib/apigen-call.ts` (a few hand-written lines per product: its sign-in and
// output helpers). A file upload (a multipart form body) takes each file field as a path
// (`--file ./sprite.png`) and goes through `callForm` with the FormData — generated only
// for a product that has one. `--check` exits 1 when the file is stale.
import fs from 'node:fs';
import { isFeature, bodyFields, formBody, isFileField } from './common.mjs';

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1] ?? true]] : acc), []),
);
const spec = JSON.parse(fs.readFileSync(args.spec ?? 'backend/openapi.json', 'utf8'));
const OUT = args.out ?? 'cli/src/commands/api.generated.ts';
const CHECK = args.check === true || args.check === 'true';
const PREFIX = args.prefix ?? '/api/v1';

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
function kind(schema) {
  if (!schema) return 'string';
  if (schema.enum) return 'string';
  const t = Array.isArray(schema.type) ? schema.type.find((x) => x !== 'null') : schema.type;
  if (t === 'integer' || t === 'number') return 'number';
  if (t === 'boolean') return 'boolean';
  if (t === 'array') return 'array';
  if (t === 'object' || schema.properties) return 'json';
  return 'string';
}

const byArea = new Map();
for (const [p, item] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(item)) {
    if (!isFeature(method, p, op)) continue;
    const segs = p.replace(PREFIX, '').split('/').filter(Boolean);
    const area = kebab(op.tags?.[0] ?? segs[0] ?? 'root');
    const rest = segs.slice(1).filter((s) => !s.startsWith('{'));
    const endsWithParam = (segs[segs.length - 1] ?? '').startsWith('{');
    const verb = { get: endsWithParam ? 'get' : 'list', post: 'create', patch: 'update', put: 'set', delete: 'delete' }[method];
    const base = rest.length ? rest.map(kebab).join('-') : verb;
    // a route that takes a JSON body always offers one (--body-json), with a flag per field
    // the spec knows (every variant's, for a body of several shapes)
    const jsonBody = op.requestBody?.content?.['application/json']?.schema;
    const body = jsonBody ? bodyFields(jsonBody) ?? { properties: {}, required: [] } : null;
    const form = formBody(op);
    const route = {
      name: base,
      verb,
      method: method.toUpperCase(),
      path: p,
      summary: op.summary ?? '',
      pathParams: (op.parameters ?? []).filter((x) => x.in === 'path').map((x) => x.name),
      query: (op.parameters ?? []).filter((x) => x.in === 'query').map((x) => ({ name: x.name, kind: kind(x.schema), required: !!x.required, choices: x.schema?.enum })),
      body: body
        ? Object.entries(body.properties).map(([name, s]) => ({ name, kind: kind(s), required: body.required.includes(name), choices: s.enum }))
        : form
          ? Object.entries(form.properties).map(([name, s]) => ({ name, kind: isFileField(s) ? 'file' : kind(s), required: (form.required ?? []).includes(name), choices: s.enum }))
          : null,
    };
    if (form) route.form = true;
    if (!byArea.has(area)) byArea.set(area, []);
    byArea.get(area).push(route);
  }
}
// Two routes of an area with the same action name (GET and PATCH /config): name each by
// its verb as well ("config" / "update-config").
for (const routes of byArea.values()) {
  const count = {};
  for (const r of routes) count[r.name] = (count[r.name] ?? 0) + 1;
  for (const r of routes) {
    if (count[r.name] > 1 && r.name !== r.verb) r.name = r.method === 'GET' ? r.name : `${r.verb}-${r.name}`;
  }
  const seen = new Set();
  for (const r of routes) {
    let n = r.name;
    let i = 2;
    while (seen.has(n)) n = `${r.name}-${i++}`;
    r.name = n;
    seen.add(n);
    delete r.verb;
  }
}
const table = [...byArea.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([area, routes]) => ({ area, routes: routes.sort((a, b) => a.name.localeCompare(b.name)) }));

let text = `// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as \`api <area> <action>\`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = ${JSON.stringify(table, null, 1)};

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? \`field-\${plain(name)}\` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(\`--\${flag(field.name)} must be a number\`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(\`--\${flag(field.name)} must be one of: \${field.choices.join(', ')}\`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(\`\${area} routes\`);
    for (const route of routes) {
      const cmd = new Command(route.name).description(\`\${route.summary} (\${route.method} \${route.path})\`);
      for (const p of route.pathParams) cmd.argument(\`<\${p}>\`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? \` (\${f.choices.join('|')})\` : f.kind === 'json' || f.kind === 'array' ? \` (\${f.kind})\` : '';
        cmd.option(f.kind === 'boolean' ? \`--\${flag(f.name)} [value]\` : \`--\${flag(f.name)} <value>\`, \`\${f.required ? 'required' : 'optional'}\${hint}\`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(\`{\${p}}\`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => \`--\${flag(f.name)}\`);
          if (missing.length) throw new Error(\`missing \${missing.join(', ')}\`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd);
    }
    api.addCommand(group);
  }
  return api;
}
`;
// A file upload: the file fields are paths, the body a multipart FormData sent through
// callForm. Only a spec with such a route gets this code, so the others' file is unchanged.
if (table.some((a) => a.routes.some((r) => r.form))) {
  const edits = [
    ["// input through failRoute (the CLI's own error output).\n", "// input through failRoute (the CLI's own error output). A file upload's body is a multipart\n// FormData, its file fields read from the paths given, sent through callForm.\n"],
    ["import { Command } from 'commander';\nimport { callRoute, failRoute } from '../lib/apigen-call.js';", "import { readFileSync } from 'node:fs';\nimport { basename } from 'node:path';\nimport { Command } from 'commander';\nimport { callForm, callRoute, failRoute } from '../lib/apigen-call.js';"],
    ["type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';", "type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json' | 'file';"],
    ['body: Field[] | null }', 'body: Field[] | null; form?: boolean }'],
    ["const hint = f.choices ?", "const hint = f.kind === 'file' ? ' (path of the file to upload)' : f.choices ?"],
    ['`--${flag(f.name)} <value>`', "`--${flag(f.name)} <${f.kind === 'file' ? 'path' : 'value'}>`"],
    ["if (route.body) cmd.option('--body-json", "if (route.body && !route.form) cmd.option('--body-json"],
    ['        let body: Record<string, unknown> | undefined;\n', [
      '        if (route.form) {',
      '          const form = new FormData();',
      '          const missing: string[] = [];',
      '          for (const f of route.body ?? []) {',
      '            const raw = opts[camel(f.name)];',
      '            if (raw === undefined) {',
      '              if (f.required) missing.push(`--${flag(f.name)}`);',
      '              continue;',
      '            }',
      "            if (f.kind === 'file') form.append(f.name, new Blob([new Uint8Array(readFileSync(String(raw)))]), basename(String(raw)));",
      '            else {',
      "              const v = value(f, raw === true ? '' : String(raw));",
      "              form.append(f.name, typeof v === 'string' ? v : JSON.stringify(v));",
      '            }',
      '          }',
      "          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);",
      '          await callForm(command, route.method, path, query, form);',
      '          return;',
      '        }',
      '        let body: Record<string, unknown> | undefined;',
      '',
    ].join('\n')],
  ];
  for (const [from, to] of edits) {
    if (!text.includes(from)) throw new Error(`apigen cli: form edit did not apply: ${from}`);
    text = text.replace(from, to);
  }
}
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
const routes = table.reduce((n, a) => n + a.routes.length, 0);
if (CHECK) {
  console.log(`apigen cli: ${routes} commands — ${current === text ? 'up to date' : 'stale'}`);
  process.exit(current === text ? 0 : 1);
}
fs.writeFileSync(OUT, text);
console.log(`apigen cli: ${routes} commands in ${table.length} areas → ${OUT}`);
