// apigen sdk — every feature route of a product as an SDK method, from its openapi.json.
//
//   node <apigen>/sdk.mjs --lang python --spec backend/openapi.json --out sdk/python/<pkg>/api_generated.py
//   node <apigen>/sdk.mjs --lang node   --spec backend/openapi.json --out sdk/node/src/api.generated.ts
//
// Writes one file with a class `GeneratedApi`: one method per route, named <area>_<action>
// (python) / <area><Action> (node), taking the path parameters, then query / body fields.
// Every call goes through the SDK client's own `_apigen_request` / `apigenRequest` (a few
// hand-written lines per SDK: its sign-in and envelope), so the generated surface signs
// requests exactly like the rest of that SDK. `--check` exits 1 when the file is stale.
import fs from 'node:fs';
import { isFeature } from './common.mjs';

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1] ?? true]] : acc), []),
);
const LANG = args.lang ?? 'python';
const spec = JSON.parse(fs.readFileSync(args.spec ?? 'backend/openapi.json', 'utf8'));
const OUT = args.out;
const CHECK = args.check === true || args.check === 'true';
const PREFIX = args.prefix ?? '/api/v1';
const BRAND = args.brand ?? spec.info?.title ?? 'product';

const words = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/[^A-Za-z0-9]+/g, ' ').trim().toLowerCase().split(/\s+/).filter(Boolean);
const snake = (s) => words(s).join('_');
const camel = (s) => words(s).map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w)).join('');
const PY_RESERVED = new Set(['json_body', 'self', 'from', 'import', 'class', 'def', 'return', 'global', 'lambda', 'type', 'id', 'in', 'is', 'not', 'or', 'and', 'if', 'else', 'for', 'while', 'with', 'as', 'pass', 'raise', 'try', 'except', 'finally', 'yield', 'del', 'assert', 'async', 'await', 'none', 'true', 'false', 'list', 'dict', 'set', 'format', 'filter', 'input', 'object', 'range', 'print', 'hash', 'max', 'min', 'all', 'any']);
const pyName = (s) => { const n = snake(s) || 'value'; return PY_RESERVED.has(n) ? `${n}_` : /^\d/.test(n) ? `n_${n}` : n; };

function pyType(schema) {
  if (!schema) return 'Any';
  if (schema.enum) return 'str';
  const t = Array.isArray(schema.type) ? schema.type.find((x) => x !== 'null') : schema.type;
  return { integer: 'int', number: 'float', boolean: 'bool', string: 'str', array: 'List[Any]', object: 'Dict[str, Any]' }[t] ?? 'Any';
}
function tsType(schema) {
  if (!schema) return 'unknown';
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  const t = Array.isArray(schema.type) ? schema.type.find((x) => x !== 'null') : schema.type;
  return { integer: 'number', number: 'number', boolean: 'boolean', string: 'string', array: 'unknown[]', object: 'Record<string, unknown>' }[t] ?? 'unknown';
}

// the same area/action names as the CLI (`api <area> <action>`)
const routes = [];
const names = new Map();
for (const [p, item] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(item)) {
    if (!isFeature(method, p)) continue;
    const segs = p.replace(PREFIX, '').split('/').filter(Boolean);
    const area = op.tags?.[0] ?? segs[0] ?? 'root';
    const rest = segs.slice(1).filter((s) => !s.startsWith('{'));
    const endsWithParam = (segs[segs.length - 1] ?? '').startsWith('{');
    const verb = { get: endsWithParam ? 'get' : 'list', post: 'create', patch: 'update', put: 'set', delete: 'delete' }[method];
    let action = rest.length ? rest.join(' ') : verb;
    const key = `${area}|${action}`;
    names.set(key, (names.get(key) ?? 0) + 1);
    const body = op.requestBody?.content?.['application/json']?.schema;
    routes.push({
      area, action, verb, method: method.toUpperCase(), path: p, summary: op.summary ?? '',
      pathParams: (op.parameters ?? []).filter((x) => x.in === 'path'),
      query: (op.parameters ?? []).filter((x) => x.in === 'query'),
      body: body && body.properties ? body : null,
      bodyRequired: !!op.requestBody?.required,
    });
  }
}
for (const r of routes) if (names.get(`${r.area}|${r.action}`) > 1 && r.action !== r.verb && r.method !== 'GET') r.action = `${r.verb} ${r.action}`;
const taken = new Set();
for (const r of routes) {
  let n = `${r.area} ${r.action}`;
  let i = 2;
  while (taken.has(n)) n = `${r.area} ${r.action} ${i++}`;
  taken.add(n);
  r.fullName = n;
}
routes.sort((a, b) => a.fullName.localeCompare(b.fullName));

function python() {
  const out = [
    `"""Every ${BRAND} feature route, one method each — generated by apigen from`,
    `backend/openapi.json. Do not edit by hand; regenerate after the API changes.`,
    '',
    'Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the',
    "client's own ``_apigen_request`` (its sign-in and response envelope).",
    '"""',
    '',
    'from __future__ import annotations',
    '',
    'from typing import Any, Dict, List, Optional',
    '',
    '',
    'class GeneratedApi:',
    `    """All ${routes.length} feature routes of the ${BRAND} API."""`,
    '',
    '    def __init__(self, client: Any) -> None:',
    '        self._client = client',
    '',
    '    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:',
    '        query = {k: v for k, v in query.items() if v is not None}',
    '        return self._client._apigen_request(method, path, query=query or None, body=body)',
  ];
  for (const r of routes) {
    const params = [];
    const doc = [`${r.summary || r.fullName} (${r.method} ${r.path}).`];
    for (const p of r.pathParams) params.push(`${pyName(p.name)}: str`);
    const kw = [];
    for (const q of r.query) kw.push({ name: q.name, py: pyName(q.name), type: pyType(q.schema), required: q.required, where: 'query' });
    if (r.body) {
      const req = new Set(r.body.required ?? []);
      for (const [name, s] of Object.entries(r.body.properties)) kw.push({ name, py: pyName(name), type: pyType(s), required: req.has(name), where: 'body', schema: s });
    }
    const sig = ['self', ...params];
    if (kw.length || r.body) sig.push('*');
    for (const k of kw) sig.push(k.required && k.where === 'query' ? `${k.py}: ${k.type}` : `${k.py}: Optional[${k.type}] = None`);
    if (r.body) sig.push('json_body: Optional[Dict[str, Any]] = None');
    if (kw.some((k) => k.where === 'body')) doc.push('', 'Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).');
    for (const k of kw.filter((x) => x.where === 'body' && x.schema?.enum)) doc.push(`${k.py}: one of ${k.schema.enum.join(', ')}`);
    let path = r.path;
    for (const p of r.pathParams) path = path.replace(`{${p.name}}`, `{_q(${pyName(p.name)})}`);
    out.push('', `    def ${pyName(r.fullName)}(${sig.join(', ')}) -> Any:`, `        """${doc.join('\n        ').replace(/"""/g, "'''")}"""`);
    const q = r.query.map((x) => `"${x.name}": ${pyName(x.name)}`).join(', ');
    if (r.body) {
      out.push('        payload: Dict[str, Any] = dict(json_body or {})');
      for (const k of kw.filter((x) => x.where === 'body')) out.push(`        if ${k.py} is not None:`, `            payload["${k.name}"] = ${k.py}`);
      for (const k of kw.filter((x) => x.where === 'body' && x.required)) out.push(`        if "${k.name}" not in payload:`, `            raise ValueError("${pyName(r.fullName)} needs ${k.py}")`);
    }
    out.push(`        return self._call("${r.method}", f"${path}", {${q}}, ${r.body ? 'payload' : 'None'})`);
  }
  out.push('', '', 'def _q(value: Any) -> str:', '    from urllib.parse import quote', '', '    return quote(str(value), safe="")', '');
  return out.join('\n');
}

function node() {
  const out = [
    `// Every ${BRAND} feature route, one method each — generated by apigen from`,
    '// backend/openapi.json. Do not edit by hand; regenerate after the API changes.',
    "// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's",
    '// own `apigenRequest` (its sign-in and response envelope).',
    '',
    'export interface ApigenTransport {',
    '  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;',
    '}',
    '',
    `/** All ${routes.length} feature routes of the ${BRAND} API. */`,
    'export class GeneratedApi {',
    '  constructor(private readonly client: ApigenTransport) {}',
    '',
    '  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {',
    '    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));',
    '    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);',
    '  }',
  ];
  for (const r of routes) {
    const params = r.pathParams.map((p) => `${camel(p.name) || 'id'}: string`);
    const fields = [];
    for (const q of r.query) fields.push(`${JSON.stringify(q.name)}${q.required ? '' : '?'}: ${tsType(q.schema)}`);
    const req = new Set(r.body?.required ?? []);
    for (const [name, s] of Object.entries(r.body?.properties ?? {})) fields.push(`${JSON.stringify(name)}${req.has(name) ? '' : '?'}: ${tsType(s)}`);
    const hasInput = fields.length > 0;
    const allOptional = !r.query.some((q) => q.required) && ![...req].length;
    if (hasInput) params.push(`input${allOptional ? '?' : ''}: { ${fields.join('; ')} }`);
    let path = r.path;
    for (const p of r.pathParams) path = path.replace(`{${p.name}}`, `\${encodeURIComponent(${camel(p.name) || 'id'})}`);
    const qNames = r.query.map((q) => q.name);
    out.push('', `  /** ${(r.summary || r.fullName).replace(/\*\//g, '* /')} (${r.method} ${r.path}) */`, `  ${camel(r.fullName)}(${params.join(', ')}): Promise<unknown> {`);
    if (hasInput) {
      out.push('    const all: Record<string, unknown> = { ...(input ?? {}) };');
      out.push(`    const query: Record<string, unknown> = {};`);
      for (const n of qNames) out.push(`    query[${JSON.stringify(n)}] = all[${JSON.stringify(n)}]; delete all[${JSON.stringify(n)}];`);
      out.push(`    return this.call(${JSON.stringify(r.method)}, \`${path}\`, query, ${r.body ? 'all' : 'undefined'});`);
    } else out.push(`    return this.call(${JSON.stringify(r.method)}, \`${path}\`, {}, undefined);`);
    out.push('  }');
  }
  out.push('}', '');
  return out.join('\n');
}

const text = LANG === 'python' ? python() : node();
const current = OUT && fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
if (CHECK) {
  console.log(`apigen sdk ${LANG}: ${routes.length} methods — ${current === text ? 'up to date' : 'stale'}`);
  process.exit(current === text ? 0 : 1);
}
fs.writeFileSync(OUT, text);
console.log(`apigen sdk ${LANG}: ${routes.length} methods → ${OUT}`);
