// Generated by apigen docs from backend/openapi.json — do not edit by hand.
import type { DocMeta } from './markdown';

export const REFERENCE_NAV: DocMeta[] = [
  {
    "slug": "api/reference",
    "title": "All routes",
    "group": "API reference (every route)",
    "href": "/docs/api/reference"
  },
  {
    "slug": "api/reference/api-keys",
    "title": "Api keys",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/api-keys"
  },
  {
    "slug": "api/reference/attachments",
    "title": "Attachments",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/attachments"
  },
  {
    "slug": "api/reference/billing",
    "title": "Billing",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/billing"
  },
  {
    "slug": "api/reference/canned-replies",
    "title": "Canned replies",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/canned-replies"
  },
  {
    "slug": "api/reference/channels",
    "title": "Channels",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/channels"
  },
  {
    "slug": "api/reference/csat",
    "title": "Csat",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/csat"
  },
  {
    "slug": "api/reference/domains",
    "title": "Domains",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/domains"
  },
  {
    "slug": "api/reference/help",
    "title": "Help",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/help"
  },
  {
    "slug": "api/reference/me",
    "title": "Me",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/me"
  },
  {
    "slug": "api/reference/profile",
    "title": "Profile",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/profile"
  },
  {
    "slug": "api/reference/public",
    "title": "Public",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/public"
  },
  {
    "slug": "api/reference/reports",
    "title": "Reports",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/reports"
  },
  {
    "slug": "api/reference/requester",
    "title": "Requester",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/requester"
  },
  {
    "slug": "api/reference/settings",
    "title": "Settings",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/settings"
  },
  {
    "slug": "api/reference/tickets",
    "title": "Tickets",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/tickets"
  },
  {
    "slug": "api/reference/webhook-subscriptions",
    "title": "Webhook subscriptions",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/webhook-subscriptions"
  }
];
