// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "592c6bd-dirty";
export const BUILD_SHA = "592c6bd";
export const BUILD_DATE = "2026-06-29T14:41:03.373Z";
