// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "f862a5e-dirty";
export const BUILD_SHA = "f862a5e";
export const BUILD_DATE = "2026-08-15T06:06:30.785Z";
